/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */


import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Najeed Habib
 */
public class BookTicket extends javax.swing.JFrame {
private String[][] available;
private String hallNumber;
private String screenNumber;
private DataControl control;
private int Total;
private int Available;
    /**
     * Creates new form BookTicket
     */
    public BookTicket(DataControl control, String hallNo, String screenNo) {
        initComponents();
        this.hallNumber = hallNo;
        this.screenNumber = screenNo;
        this.control = control;
        ArrayList availableSeats = new ArrayList();
        availableSeats = control.getAvailableSeats(hallNo, screenNo);
        this.Total = control.getTotalSeatsNumber();
        this.Available = control.getAvailableSeatsNumber();
        jLabel1.setText("Available Seats: "+availableSeats.size()/2);
        jLabel2.setText("Total Seats: 50");
        available = new String[availableSeats.size()/2][2];
        int row = 0;
        int seat = 1;
        for(int i=0 ; i<availableSeats.size()/2; i++){
            available[i][0] = (String) availableSeats.get(row);
            available[i][1] = (String) availableSeats.get(seat);
            row += 2;
            seat += 2;
        }
                jTable1.setModel(new javax.swing.table.DefaultTableModel(
            available,
            new String [] {
                "Row Number", "Seat Number"
            }
        ));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton1.setText("Book Ticket");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setText("Available Seats:");

        jLabel2.setText("Total Seats:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(232, 232, 232)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(97, 97, 97)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        JTextField Row = new JTextField();
        JTextField Seat = new JTextField();
        boolean condition = false;
        Object[] message = {
            "Row Number:", Row,
            "Seat Number:", Seat
            
        };
        int option = JOptionPane.showConfirmDialog(null, message, "Enter Row And Seat Number", JOptionPane.OK_CANCEL_OPTION);
        if (option == JOptionPane.OK_OPTION) {
            for(int i = 0; i < available.length ; i++){
                if (available[i][0].equals(Row.getText())&&available[i][1].equals(Seat.getText())) {
                    control.generateTicket(hallNumber, screenNumber, Row.getText(), Seat.getText());
                    this.setVisible(false);
                    condition = true;
                    
                    break;
                }
                
            }
            if (!condition) {
                JOptionPane.showMessageDialog(null,"Seat and Row Number NOT Exist");
                condition = false;
            }
        } 
        else {
        JOptionPane.showMessageDialog(null,"No Seat And Row Number Selected");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
 

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
